package com.wa.apiaccount.core.model.domain;

import java.util.Date;

public class SettlePactFee extends SettlePactFeeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.pact_code
     *
     * @mbg.generated
     */
    private String pactCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.pact_type
     *
     * @mbg.generated
     */
    private String pactType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.pact_code
     *
     * @return the value of settle_pact_fee.pact_code
     *
     * @mbg.generated
     */
    public String getPactCode() {
        return pactCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.pact_code
     *
     * @param pactCode the value for settle_pact_fee.pact_code
     *
     * @mbg.generated
     */
    public void setPactCode(String pactCode) {
        this.pactCode = pactCode == null ? null : pactCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.pact_type
     *
     * @return the value of settle_pact_fee.pact_type
     *
     * @mbg.generated
     */
    public String getPactType() {
        return pactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.pact_type
     *
     * @param pactType the value for settle_pact_fee.pact_type
     *
     * @mbg.generated
     */
    public void setPactType(String pactType) {
        this.pactType = pactType == null ? null : pactType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.insert_time
     *
     * @return the value of settle_pact_fee.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.insert_time
     *
     * @param insertTime the value for settle_pact_fee.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.operator
     *
     * @return the value of settle_pact_fee.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.operator
     *
     * @param operator the value for settle_pact_fee.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_pact_fee
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettlePactFee other = (SettlePactFee) that;
        return (this.getMerNo() == null ? other.getMerNo() == null : this.getMerNo().equals(other.getMerNo()))
            && (this.getAcctDate() == null ? other.getAcctDate() == null : this.getAcctDate().equals(other.getAcctDate()))
            && (this.getTranCode() == null ? other.getTranCode() == null : this.getTranCode().equals(other.getTranCode()))
            && (this.getFeeType() == null ? other.getFeeType() == null : this.getFeeType().equals(other.getFeeType()))
            && (this.getFeeValue() == null ? other.getFeeValue() == null : this.getFeeValue().equals(other.getFeeValue()))
            && (this.getPactCode() == null ? other.getPactCode() == null : this.getPactCode().equals(other.getPactCode()))
            && (this.getPactType() == null ? other.getPactType() == null : this.getPactType().equals(other.getPactType()))
            && (this.getInsertTime() == null ? other.getInsertTime() == null : this.getInsertTime().equals(other.getInsertTime()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_pact_fee
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerNo() == null) ? 0 : getMerNo().hashCode());
        result = prime * result + ((getAcctDate() == null) ? 0 : getAcctDate().hashCode());
        result = prime * result + ((getTranCode() == null) ? 0 : getTranCode().hashCode());
        result = prime * result + ((getFeeType() == null) ? 0 : getFeeType().hashCode());
        result = prime * result + ((getFeeValue() == null) ? 0 : getFeeValue().hashCode());
        result = prime * result + ((getPactCode() == null) ? 0 : getPactCode().hashCode());
        result = prime * result + ((getPactType() == null) ? 0 : getPactType().hashCode());
        result = prime * result + ((getInsertTime() == null) ? 0 : getInsertTime().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        return result;
    }
}