package com.wd.apiaccount.model.domain;

import java.math.BigDecimal;

public class SettlePactFeeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.mer_no
     *
     * @mbg.generated
     */
    private String merNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.acct_date
     *
     * @mbg.generated
     */
    private String acctDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.tran_code
     *
     * @mbg.generated
     */
    private String tranCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.fee_type
     *
     * @mbg.generated
     */
    private String feeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_pact_fee.fee_value
     *
     * @mbg.generated
     */
    private BigDecimal feeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.mer_no
     *
     * @return the value of settle_pact_fee.mer_no
     *
     * @mbg.generated
     */
    public String getMerNo() {
        return merNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.mer_no
     *
     * @param merNo the value for settle_pact_fee.mer_no
     *
     * @mbg.generated
     */
    public void setMerNo(String merNo) {
        this.merNo = merNo == null ? null : merNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.acct_date
     *
     * @return the value of settle_pact_fee.acct_date
     *
     * @mbg.generated
     */
    public String getAcctDate() {
        return acctDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.acct_date
     *
     * @param acctDate the value for settle_pact_fee.acct_date
     *
     * @mbg.generated
     */
    public void setAcctDate(String acctDate) {
        this.acctDate = acctDate == null ? null : acctDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.tran_code
     *
     * @return the value of settle_pact_fee.tran_code
     *
     * @mbg.generated
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.tran_code
     *
     * @param tranCode the value for settle_pact_fee.tran_code
     *
     * @mbg.generated
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode == null ? null : tranCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.fee_type
     *
     * @return the value of settle_pact_fee.fee_type
     *
     * @mbg.generated
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.fee_type
     *
     * @param feeType the value for settle_pact_fee.fee_type
     *
     * @mbg.generated
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_pact_fee.fee_value
     *
     * @return the value of settle_pact_fee.fee_value
     *
     * @mbg.generated
     */
    public BigDecimal getFeeValue() {
        return feeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_pact_fee.fee_value
     *
     * @param feeValue the value for settle_pact_fee.fee_value
     *
     * @mbg.generated
     */
    public void setFeeValue(BigDecimal feeValue) {
        this.feeValue = feeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_pact_fee
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettlePactFeeKey other = (SettlePactFeeKey) that;
        return (this.getMerNo() == null ? other.getMerNo() == null : this.getMerNo().equals(other.getMerNo()))
            && (this.getAcctDate() == null ? other.getAcctDate() == null : this.getAcctDate().equals(other.getAcctDate()))
            && (this.getTranCode() == null ? other.getTranCode() == null : this.getTranCode().equals(other.getTranCode()))
            && (this.getFeeType() == null ? other.getFeeType() == null : this.getFeeType().equals(other.getFeeType()))
            && (this.getFeeValue() == null ? other.getFeeValue() == null : this.getFeeValue().equals(other.getFeeValue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_pact_fee
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerNo() == null) ? 0 : getMerNo().hashCode());
        result = prime * result + ((getAcctDate() == null) ? 0 : getAcctDate().hashCode());
        result = prime * result + ((getTranCode() == null) ? 0 : getTranCode().hashCode());
        result = prime * result + ((getFeeType() == null) ? 0 : getFeeType().hashCode());
        result = prime * result + ((getFeeValue() == null) ? 0 : getFeeValue().hashCode());
        return result;
    }
}